version: '3.7'

services:
  web:
    build: 
      context: ./.docker
      dockerfile: nginx.dockerfile
    ports:
      - "8080:8080"
    restart: always
    volumes:
     - ./src:/var/www/html
    environment:
      - WEB_PORT=8080
    depends_on:
      - fpm

  # open when needed
  db:
    image: mysql:5.6
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=mydb_user
      - MYSQL_PASSWORD=password
    ports:
      - "3340:3306"
  
  fpm:
    build: 
      context: ./.docker
      dockerfile: fpm.dockerfile
    ports: 
     - "9000:9000"
    volumes:
      - ./src:/var/www/html
